add nm-online check to avoid costly pinging and make default

diff --git a/scripts/msmtpq/msmtpq b/scripts/msmtpq/msmtpq
--- a/scripts/msmtpq/msmtpq
+++ b/scripts/msmtpq/msmtpq
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-
 ##--------------------------------------------------------------
 ##
 ##  msmtpq : queue funtions to both use & manage the msmtp queue,
@@ -34,11 +33,14 @@
 
 ## msmtpq now uses the following environment variables :
 ##   EMAIL_CONN_NOTEST   if set will suppress any testing for a connection
-##   EMAIL_CONN_TEST     if unset or =p will use a ping test (debian.org) for a connection
+##   EMAIL_CONN_TEST     if unset or =nm will use NetworkManager (nm-online) to test for a connection
+##                       if =p will use a ping test (debian.org) for a connection
 ##                       if =P will use a fast ping test (8.8.8.8) for a connection
 ##                       if =n will use netcat (nc) to test for a connection
 ##                       if =s will use bash sockets to test for a connection
 ##   EMAIL_QUEUE_QUIET   if set will cause suppression of messages and 'chatter'
+
+EMAIL_CONN_TEST=nm
 
 ## two essential patches by Philipp Hartwig
 ## 19 Oct 2011 & 27 Oct 2011
@@ -172,7 +174,14 @@ lock_queue() {        # <-- '-u' to remove lockfile
 ## returns t/f (0/1)
 connect_test() {
   if [ -z "$EMAIL_CONN_TEST" ] || \
-     [ "$EMAIL_CONN_TEST" = 'p' ] ; then                       # use ping test (default)
+     [ "$EMAIL_CONN_TEST" = 'nm' ] ; then                      # use NetworkManager (nm-online) test (default)
+    # must, of course, have nm-online installed
+    which nm-online >/dev/null 2>&1 || \
+      log -e 1 "msmtpq : can't find nm-online executable "     # if not found - complain ; quit
+    echo 'using nm-online'
+    set -x
+    'nm-online' -xq || return 1
+  elif [ "$EMAIL_CONN_TEST" = 'p' ] ; then                     # use ping test
     # verify net connection - ping ip address of debian.org
     # would ping -qnc2 -w4 be better ?
     # would ping -qnc1 -w10 or -w20 be better ?
